import os
import streamlit as st
import pandas as pd
import joblib

# Load the model committed by the pipeline (sits next to this file)
model_path = os.path.join(os.path.dirname(__file__), "best_SuperKart_model_v1.joblib")
model = joblib.load(model_path)

# Streamlit UI for Revenue Prediction
st.title("Revenue Prediction")
st.write("Fill the Product details below to predict the revenue generated by them")

# Collect user input
Product_Weight = st.number_input("Product Weight", min_value=0.01, value=30000.0)
Product_Sugar_Content = st.number_input("Product Sugar Content", min_value=0.01, value=30000.0)
Product_Allocated_Area = st.number_input("Product_Allocated_Area",  min_value=0.01, value=30000.0)
Product_Type =  st.selectbox("Product_Type", ["Baking Goods", "Breads", "Breakfast", "Canned", "Dairy", "Frozen Foods", "Fruits and Vegetables", 
                                              "Hard Drinks", "Health and Hygiene", "Household", "Meat", "Others", "Seafood", "Snack Foods", 
                                              "Soft Drinks", "Starchy Foods"])
Product_MRP = st.number_input("Product_MRP",  min_value=0.01, value=30000.0)
current_year = datetime.datetime.now().year
Store_Establishment_Year = st.slider("Store_Establishment_Year", min_value=1980, max_value=current_year, value=2010, step=1,)
Store_Size =  st.selectbox("Store_Size", ["High", "Medium", "Small"])
Store_Location_City_Type = st.selectbox("Store_Location_City_Type", ["Tier 1", "Tier 2", "Tier 3", ])
Store_Type = st.selectbox("Store_Type", ["Departmental Store", "Food Mart", "Supermarket Type1", "Supermarket Type2"])


# ----------------------------
# Prepare input data
# ----------------------------
input_data = pd.DataFrame([{
    'Product_Weight'  : Product_Weight,
    'Product_Sugar_Content'  : Product_Sugar_Content,
    'Product_Allocated_Area'  : Product_Allocated_Area,
    'Product_Type'  : Product_Type ,
    'Product_MRP'  : Product_MRP,
    'current_year'  : current_year,
    'Store_Establishment_Year'  : Store_Establishment_Year ,
    'Store_Size'  : Store_Size,
    'Store_Location_City_Type'  : Store_Location_City_Type ,
    'Store_Type'  : Store_Type
}])

# Predict button
if st.button("Predict"):
    # Get continuous revenue prediction from regression model
    predicted_revenue = model.predict(input_data)[0]
    # Ensure predicted revenue isn't negative (common in regression)
    predicted_revenue = max(0.0, float(predicted_revenue))
    # Display prediction formatted as currency
    st.success(f"Predicted Revenue: **${predicted_revenue:,.2f}**")
